**Introduciton**

I have made the csv as dirty as possible to demonstrate data cleaning skills

*Import Libraries*

In [3]:
import pandas as pd
from utils.py import

Read .csv file and load into variable **df**

In [5]:
df = pd.read_csv("data/TC_Aug1923_2024.csv")

In [6]:
df

,Timestamp,Email Address,"Name of Participant (First Name, Last Name)",Nick Name,Aug 19,Aug 20,Aug 21,Aug 22,Aug 23,Payment,...,School Attending,Choose your group,Main Contact e-mail address,Main Contact phone number,Optional Second e-mail address,Optional Second phone number,Once booking made payments can be made to the following bank account: Top Flight Basketball Company Limited - HSBC – 023-697444-838. Please send us proof of payment to INFO@TOPFLIGHTHONGKONG.COM with your child's name indicated.,"I, the parent or guardian of the player named above, acknowledge that when my child is playing/participating/performing basketball activities s/he may suffer injury. I release Top Flight Basketball Co. Ltd from any liability concerning any injury or harm suffered by my child during or as a consequence of participation in the activities.","I, the parent or legal guardian of the child named above grant Top Flight basketball Co. Ltd my permission to use the photographs taken at basketball sessions for any legal use, including but not limited to: publicity, copyright purposes, illustration, advertising, and web content. Furthermore, I understand that no royalty, fee or other compensation shall become payable to me by reason of such use.","Thank your for signing up, please add any comments you would like us to know about."
0,7/16/2024 13:31:46,pacificocean1977@gmail.com,Deniz Kabadayi,Deniz,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,DSC İnternational School,August 12-16 (Mon-Fri) at ESF / Ages 6-13 - 9:...,pacificocean1977@gmail.com,98099861,zafer.kabadayi@schindler.com,91918111,Confirm,Confirm,Confirm,NaN
1,7/16/2024 14:01:06,chewku@gmail.com,"Damian, Chew",Damian,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,ESF Island School,August 12-16 (Mon-Fri) at ESF / Ages 6-13 - 9:...,Chewku@gmail.com,91836859,Chewdjm@gmail.com,91856675,Confirm,Confirm,Confirm,NaN
2,7/26/2024 13:45:05,joyce_mslai@hotmail.com,Jonas Chiu,Jonas,TRUE,TRUE,FALSE,TRUE,TRUE,"$1,800.00",...,South Island School,NaN,joyce_mslai@hotmail.com,92633705,NaN,NaN,Confirm,Confirm,Confirm,NaN
3,7/27/2024 6:34:32,Tereza_d@hotmail.com,Ethan Cheng,Ethan,TRUE,TRUE,FALSE,FALSE,TRUE,NaN,...,HKIS,NaN,Tereza_d@hotmail.com,Tereza_d@hotmail.com,NaN,NaN,Confirm,Confirm,Confirm,NaN
4,7/27/2024 6:36:31,Tereza_d@hotmail.com,Elliot Cheng,Elliot,TRUE,TRUE,TRUE,TRUE,TRUE,NaN,...,HKIS,NaN,Tereza_d@hotmail.com,Tereza_d@hotmail.com,NaN,NaN,Confirm,Confirm,Confirm,NaN
5,7/30/2024 4:16:19,oliviahwang@gmail.com,Luca Monguillot,Luca,TRUE,TRUE,TRUE,FALSE,TRUE,"$1,600.00",...,IMS,NaN,oliviahwang@gmail.com,96694587,NaN,NaN,Confirm,Confirm,Confirm,As discussed with Agnes Luca will attend daily...
6,7/30/2024 6:38:05,pchan@everpro.com,Adam Lai,Adam,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,HKIS,NaN,linlydia2@gmail.com,63489298,pchan@everpro.com,97595764,Confirm,Confirm,NaN,NaN
7,7/31/2024 6:49:26,natchy.nish@gmail.com,Alexander Junas,Alex,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,Silvermine bay school,NaN,Natchy.nish@gmail.com,65363777,NaN,NaN,Confirm,Confirm,Confirm,NaN
8,8/2/2024 11:00:47,cathypudding@yahoo.com.hk,Ryan Jenson LAM,Ryan,FALSE,FALSE,FALSE,FALSE,FALSE,NaN,...,French International School,NaN,cathypudding@yahoo.com.hk,94406698,NaN,NaN,Confirm,Confirm,Confirm,NaN
9,8/2/2024 11:52:26,amandreaming@yahoo.com.hk,Loic VAN HOOF,Loic,TRUE,TRUE,TRUE,TRUE,TRUE,"$1,800.00",...,Victoria Shanghai Academy,NaN,amandreaming@yahoo.com.hk,59739596,NaN,NaN,Confirm,Confirm,Confirm,NaN
10,8/2/2024 12:15:57,katiewc@gmail.com,Tristan Tsun,Tristan,TRUE,TRUE,FALSE,FALSE,TRUE,"$2,000.00",...,Hkis,NaN,Katiewc@gmail.com,90434700,NaN,NaN,Confirm,Confirm,Confirm,NaN
11,8/5/2024 6:26:46,nky.carolyn@gmail.com,Charles Cheung,Charles,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,Hong Kong Harrow International School,NaN,nky.carolyn@gmail.com,91089175,NaN,NaN,Confirm,Confirm,Confirm,Kindly please put Charles in a group with Loic...
12,8/5/2024 7:01:02,oscaryliu@hotmail.com,Nathan Liu,Shuai Shuai,FALSE,FALSE,FALSE,FALSE,FALSE,NaN,...,The ISF School,NaN,wenda_wu@hotmail.com,65755124,oscaryliu@hotmail.com,+852 65949890,Confirm,Confirm,Confirm,NaN
13,8/13/2024 12:27:02,andreaoychu@gmail.com,Colin Lai,Colin,FALSE,TRUE,FALSE,TRUE,FALSE,$720.00,...,CDNIS,NaN,andreaoychu@gmail.com,97764969,NaN,NaN,Confirm,Confirm,Confirm,NaN
14,8/15/2024 13:20:20,naoko.eto@gmail.com,Sou Kimura,Sou,TRUE,TRUE,TRUE,TRUE,TRUE,"$1,800.00",...,YMCA Christian Academy,NaN,naoko.eto@gmail.com,97667995,gen8104@gmail.com,97665920,Confirm,Confirm,Confirm,NaN
15,8/18/2024 2:09:55,clinbox8@gmail.com,George Tilton/Theo Tilton,George/Theo,TRUE,TRUE,FALSE,TRUE,FALSE,"$2,000.00",...,Chinese International School,NaN,clinbox8@gmail.com,56683625,NaN,NaN,Confirm,Confirm,Confirm,"George can only come on Mon, Tues and Thurs of..."
16,8/18/2024 3:43:37,jocsonco@yahoo.com,Chace Co,Chace,TRUE,FALSE,FALSE,FALSE,FALSE,NaN,...,CIS,NaN,jocsonco@yahoo.com,96195612,NaN,NaN,Confirm,Confirm,Confirm,Chace can go Monday and Friday for sure. He is...
17,8/18/2024 9:34:53,helen.colquhoun@dlapiper.com,Callum Houdijk,Callum,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,Kellett,NaN,helen.colquhoun@dlapiper.com,60860913,NaN,NaN,Confirm,Confirm,Confirm,NaN
18,8/18/2024 13:37:18,hidelisa@hotmail.com,Timeo daniels,Timeo,TRUE,FALSE,TRUE,FALSE,TRUE,"$1,200.00",...,Canadian international school,NaN,hidelisa@hotmail.com,66254721,NaN,NaN,Confirm,Confirm,Confirm,"Hello, can timeo please do 2 or 3 classes this..."
19,8/18/2024 13:52:32,angieechow@hotmail.com,Brayden Ho,Brayden,TRUE,TRUE,FALSE,FALSE,TRUE,"$2,000.00",...,ESF SIS,NaN,angieechow@hotmail.com,93091613,NaN,NaN,Confirm,Confirm,Confirm,"Joining 19/8, 20/8, 23/8 , 3 classes only"
20,8/18/2024 15:26:00,carolthchan@hotmail.com,Jayden Zhou,Jayden,FALSE,FALSE,FALSE,TRUE,TRUE,"$2,000.00",...,HKIS,NaN,carolthchan@hotmail.com,93876630,NaN,NaN,Confirm,Confirm,Confirm,NaN
21,8/18/2024 18:01:33,daisy.ning@gmail.com,Zachary Fung,Zach,FALSE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,Canadian International School,NaN,daisy.ning@gmail.com,91092709,NaN,NaN,Confirm,Confirm,Confirm,NaN
22,8/18/2024 18:39:17,yongjun.tang@gmail.com,"Tang, Athena; Tang, Joyce","Athena, Joyce",FALSE,FALSE,FALSE,FALSE,FALSE,NaN,...,Chinese International School,NaN,yongjun.tang@gmail.com,68471538,NaN,NaN,Confirm,Confirm,Confirm,NaN
23,8/18/2024 18:52:33,irislileong@gmail.com,Wesley Leong,Wesley,FALSE,TRUE,TRUE,FALSE,FALSE,$400.00,...,Harrow School,NaN,Wesleyleong13@gmail.com,95428383,NaN,NaN,Confirm,Confirm,Confirm,Can Wesley sign up for one trial lesson?
24,8/19/2024 4:36:31,choiaky@gmail.com,Lachlan Lo,Lachlan,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,SJPS,NaN,choiaky@gmail.com,63325928,NaN,NaN,Confirm,Confirm,Confirm,NaN
25,8/19/2024 7:35:04,celinec@gmail.com,Blake YAM,Blake,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,AISHK,NaN,celinec@gmail.com,91938660,NaN,93027602,Confirm,Confirm,Confirm,NaN
26,8/19/2024 7:35:53,celinec@gmail.com,Mackenzie Yam,Mackenzie,TRUE,TRUE,TRUE,TRUE,TRUE,"$2,000.00",...,AISHK,NaN,celinec@gmail.com,91938660,NaN,93027602,Confirm,Confirm,Confirm,NaN
27,8/19/2024 9:53:38,sing.wong@yahoo.com.hk,Klement Wong,Klement,TRUE,TRUE,TRUE,TRUE,FALSE,"$2,000.00",...,Australian International School,NaN,sing.wong@yahoo.com.hk,60851057,NaN,62310579,Confirm,Confirm,Confirm,NaN
28,8/19/2024 13:34:27,daisychui@yahoo.com,Cohen cheng,Cohe,TRUE,FALSE,TRUE,FALSE,FALSE,"$1,200.00",...,CIS,NaN,daisychui@yahoo.com,98222233,Chihcc2029@student.cis.edu.hk,95559245,Confirm,Confirm,Confirm,Cohen will attend 3 sessions so I have made $1...
29,8/19/2024 15:02:07,naoko.eto@gmail.com,Midori Kimura,Midori,TRUE,TRUE,TRUE,TRUE,FALSE,"$2,000.00",...,YMCA Christian Academy,NaN,naoko.eto@gmail.com,97667995,gen8104@gmail.com,97665920,Confirm,Confirm,Confirm,NaN
30,NaN,NaN,Oscar Gustave Breidenbach,Oscar,TRUE,TRUE,TRUE,TRUE,TRUE,NaN,...,NaN,NaN,slbreidenbach@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,Caleb Wang,Caleb,FALSE,FALSE,TRUE,FALSE,TRUE,$800.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,Andrew,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,Anthony,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,Notes:,Total,24,24,21,20,22,"$43,320.00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,Marked in Red are those who have not been seen...,Percentage Attendance / Paid,75.00%,75.00%,65.63%,62.50%,68.75%,78.13%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,- Follow Up Oscar Email and Payment \n- Coach ...,Total Havent Paid,NaN,NaN,NaN,NaN,NaN,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,Jersey Sizes,Count,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,28,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,30,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,32,3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,34,6,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,36,3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,38,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,40,4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,42,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

We can see from this dataframe that there is alot of work to be done. There are many missing values,

Remove players who did not attend

In [9]:
# DNA = Did Not Attend
DNA = df[(df[['Aug 19', 'Aug 20', 'Aug 21', 'Aug 22', 'Aug 23']] == "FALSE").all(axis=1)]

# Extract the names of the participants meeting the condition
names = DNA['Name of Participant (First Name, Last Name)']
names = names.to_list()
names
df = df[~df['Name of Participant (First Name, Last Name)'].isin(names)]

Add names of players who did attend

In [11]:
df.at[32, 'Full Name'] = 'Andrew Atayde'
df.at[33, 'Full Name'] = 'Anthony Atayde'
df.iloc[32, 3:8] = 'TRUE'
df.iloc[33, 3:8] = 'TRUE'

/var/folders/k8/54zwc4911p16cz5tw9zrk4vh0000gn/T/ipykernel_1298/1808222309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.at[32, 'Full Name'] = 'Andrew Atayde'

In [12]:
df = df[["Name of Participant (First Name, Last Name)", "Date of Birth", "Gender"]]

In [13]:
df

          Name of Participant (First Name, Last Name) Date of Birth  Gender
0                                      Deniz Kabadayi    12/22/2011  Female
1                                        Damian, Chew     4/26/2012    Male
2                                          Jonas Chiu     9/12/2012    Male
3                                         Ethan Cheng     4/10/2012    Male
4                                        Elliot Cheng    10/27/2014    Male
5                                    Luca Monguillot      8/22/2015    Male
6                                            Adam Lai    10/17/2014    Male
7                                     Alexander Junas      6/7/2013    Male
9                                       Loic VAN HOOF     9/19/2017    Male
10                                       Tristan Tsun     2/27/2016    Male
11                                     Charles Cheung     5/19/2017    Male
13                                          Colin Lai     3/11/2013    Male
14                                        Sou Kimura       6/6/2014    Male
15                          George Tilton/Theo Tilton     8/21/2011    Male
16                                           Chace Co     6/19/2011    Male
17                                     Callum Houdijk      2/1/2013    Male
18                                     Timeo daniels      4/21/2010    Male
19                                         Brayden Ho     9/20/2011    Male
20                                        Jayden Zhou     3/23/2016    Male
21                                       Zachary Fung      8/5/2010    Male
23                                       Wesley Leong     5/13/2008    Male
24                                         Lachlan Lo     6/11/2018    Male
25                                          Blake YAM    12/17/2012    Male
26                                      Mackenzie Yam     8/31/2015  Female
27                                       Klement Wong    10/13/2015    Male
28                                       Cohen cheng      9/24/2010    Male
29                                     Midori Kimura       4/8/2018  Female
30                          Oscar Gustave Breidenbach           NaN    Male
31                                         Caleb Wang           NaN    Male
32                                                NaN           NaN     NaN
33                                                NaN           NaN     NaN
34                                                NaN           NaN     NaN
35                                                NaN           NaN     NaN
36                                                NaN           NaN     NaN
37                                                NaN           NaN     NaN
38                                                NaN           NaN     NaN
39                                                NaN           NaN     NaN
40                                             Notes:  Average Age      NaN
41  Marked in Red are those who have not been seen...       Max Age     NaN
42  - Follow Up Oscar Email and Payment \n- Coach ...       Min Age     NaN
43                                                NaN        Male %     NaN
44                                                NaN      Female %     NaN
45                                                NaN           NaN     NaN
46                                                NaN           NaN     NaN
47                                                NaN           NaN     NaN
48                                                NaN           NaN     NaN
49                                                NaN           NaN     NaN
50                                                NaN           NaN     NaN
51                                                NaN           NaN     NaN
52                                                NaN           NaN     NaN

Lets make the format of the Names more uniform

In [16]:
# Apply the replacement directly within a lambda function, handling NaN values
df['Standardized Name'] = df['Name of Participant (First Name, Last Name)'].apply(lambda x: x.replace('/Theo Tilton', '').replace(',', '') if isinstance(x, str) else x)


df

,"Name of Participant (First Name, Last Name)",Date of Birth,Gender,Standardized Name
0,Deniz Kabadayi,12/22/2011,Female,Deniz Kabadayi
1,"Damian, Chew",4/26/2012,Male,Damian Chew
2,Jonas Chiu,9/12/2012,Male,Jonas Chiu
3,Ethan Cheng,4/10/2012,Male,Ethan Cheng
4,Elliot Cheng,10/27/2014,Male,Elliot Cheng
5,Luca Monguillot,8/22/2015,Male,Luca Monguillot
6,Adam Lai,10/17/2014,Male,Adam Lai
7,Alexander Junas,6/7/2013,Male,Alexander Junas
9,Loic VAN HOOF,9/19/2017,Male,Loic VAN HOOF
10,Tristan Tsun,2/27/2016,Male,Tristan Tsun
11,Charles Cheung,5/19/2017,Male,Charles Cheung
13,Colin Lai,3/11/2013,Male,Colin Lai
14,Sou Kimura,6/6/2014,Male,Sou Kimura
15,George Tilton/Theo Tilton,8/21/2011,Male,George Tilton
16,Chace Co,6/19/2011,Male,Chace Co
17,Callum Houdijk,2/1/2013,Male,Callum Houdijk
18,Timeo daniels,4/21/2010,Male,Timeo daniels
19,Brayden Ho,9/20/2011,Male,Brayden Ho
20,Jayden Zhou,3/23/2016,Male,Jayden Zhou
21,Zachary Fung,8/5/2010,Male,Zachary Fung
23,Wesley Leong,5/13/2008,Male,Wesley Leong
24,Lachlan Lo,6/11/2018,Male,Lachlan Lo
25,Blake YAM,12/17/2012,Male,Blake YAM
26,Mackenzie Yam,8/31/2015,Female,Mackenzie Yam
27,Klement Wong,10/13/2015,Male,Klement Wong
28,Cohen cheng,9/24/2010,Male,Cohen cheng
29,Midori Kimura,4/8/2018,Female,Midori Kimura
30,Oscar Gustave Breidenbach,NaN,Male,Oscar Gustave Breidenbach
31,Caleb Wang,NaN,Male,Caleb Wang
32,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
40,Notes:,Average Age,NaN,Notes:
41,Marked in Red are those who have not been seen...,Max Age,NaN,Marked in Red are those who have not been seen...
42,- Follow Up Oscar Email and Payment \n- Coach ...,Min Age,NaN,- Follow Up Oscar Email and Payment \n- Coach ...
43,NaN,Male %,NaN,NaN
44,NaN,Female %,NaN,NaN
45,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN

In [17]:
df.drop(columns=['Name of Participant (First Name, Last Name)'], inplace=True)

In [18]:
df

   Date of Birth  Gender                                  Standardized Name
0     12/22/2011  Female                                     Deniz Kabadayi
1      4/26/2012    Male                                        Damian Chew
2      9/12/2012    Male                                         Jonas Chiu
3      4/10/2012    Male                                        Ethan Cheng
4     10/27/2014    Male                                       Elliot Cheng
5      8/22/2015    Male                                   Luca Monguillot
6     10/17/2014    Male                                           Adam Lai
7       6/7/2013    Male                                    Alexander Junas
9      9/19/2017    Male                                      Loic VAN HOOF
10     2/27/2016    Male                                       Tristan Tsun
11     5/19/2017    Male                                     Charles Cheung
13     3/11/2013    Male                                          Colin Lai
14      6/6/2014    Male                                        Sou Kimura
15     8/21/2011    Male                                      George Tilton
16     6/19/2011    Male                                           Chace Co
17      2/1/2013    Male                                     Callum Houdijk
18     4/21/2010    Male                                     Timeo daniels
19     9/20/2011    Male                                         Brayden Ho
20     3/23/2016    Male                                        Jayden Zhou
21      8/5/2010    Male                                       Zachary Fung
23     5/13/2008    Male                                       Wesley Leong
24     6/11/2018    Male                                         Lachlan Lo
25    12/17/2012    Male                                          Blake YAM
26     8/31/2015  Female                                      Mackenzie Yam
27    10/13/2015    Male                                       Klement Wong
28     9/24/2010    Male                                       Cohen cheng
29      4/8/2018  Female                                     Midori Kimura
30           NaN    Male                          Oscar Gustave Breidenbach
31           NaN    Male                                         Caleb Wang
32           NaN     NaN                                                NaN
33           NaN     NaN                                                NaN
34           NaN     NaN                                                NaN
35           NaN     NaN                                                NaN
36           NaN     NaN                                                NaN
37           NaN     NaN                                                NaN
38           NaN     NaN                                                NaN
39           NaN     NaN                                                NaN
40  Average Age      NaN                                             Notes:
41       Max Age     NaN  Marked in Red are those who have not been seen...
42       Min Age     NaN  - Follow Up Oscar Email and Payment \n- Coach ...
43        Male %     NaN                                                NaN
44      Female %     NaN                                                NaN
45           NaN     NaN                                                NaN
46           NaN     NaN                                                NaN
47           NaN     NaN                                                NaN
48           NaN     NaN                                                NaN
49           NaN     NaN                                                NaN
50           NaN     NaN                                                NaN
51           NaN     NaN                                                NaN
52           NaN     NaN                                                NaN

In [19]:
df = df = df.drop(df.index[31:])

Let's Create a Function to anonymize names by adding a Student ID column and remove personal information

In [ ]:
student_id_cols["Student ID"] = df.apply(generate_student_id, axis=1)